# https://github.com/discordjs/discord.js/blob/main/.github/workflows/publish-dev.yml

name: Publish dev
on: [ push ]

jobs:
  deprecate:
    name: Deprecate
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ankhgerel' && !contains(github.event.commits[0].message, '[skipCI]')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn --immutable

      - name: Deprecate versions
        run: 'yarn npm-deprecate --name "*dev*" --package @anhgerel/logger @anhgerel/debug-tool'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish:
    name: Publish
    needs: [ deprecate ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: '@anhgerel/logger'
            folder: 'logger'
          - package: '@anhgerel/debug-tool'
            folder: 'debugTool'
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skipCI]') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node.js v17
        uses: actions/setup-node@v3
        with:
          node-version: 17
          registry-url: https://registry.npmjs.org/
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn --immutable && npm i @favware/cliff-jumper -g

      - name: Build dependencies
        run: yarn build

      - name: Publish package
        run: |
          yarn workspace ${{ matrix.package }} publish --preid "dev.$(git rev-parse --short HEAD)"
          yarn workspace ${{ matrix.package }} npm publish --access public --tag dev || true
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
